---
apiVersion: apps/v1
kind: Deployment
metadata:
# Define the deployment name
  name: reactdeployment
spec:
# Define the number of PODS
  replicas: 4
  strategy:
    type: Recreate
  # Define the Selector
  selector:
    matchLabels:
      app: reactdjango
  template:
    metadata:
      name: reactdjango
      labels:
        app: reactdjango
    spec:
    # container details
      containers:
      - name: reactdjangocontainer
      # Image form dockerHub
        image: rjthapaa/reactdjango
        ports:
        # Define the Port
          - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: reactdjangosvc
spec:
# Define the service type
  type: NodePort
  selector:
    app: reactdjango
  ports:
  # Define the Port
    - port: 80
      targetPort: 8001
      nodePort: 30785
...
